### Environment: Development
@dev_base_url = http://localhost:3000

### Environment: Production
@prod_base_url = https://wardro-prod.onrender.com

### Base URL
@base_url = {{dev_base_url}}

### Healthcheck API
GET {{base_url}}/api/healthcheck

# Entity: User
This entity represents a user.

### Get all users
GET {{base_url}}/api/users/user_2mmu2aI1SXxHpvJ3K6e9LWj0CH5

### Create a user
POST {{base_url}}/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@gmail.com",
  "clerkId": "user_2mmu2aI1SXxHpvJ3K6e9LWj0CH6"
}

# Entity: Wardrobe
This entity represents a wardrobe that belongs to a user.

### Create Wardrobe
POST {{base_url}}/api/wardrobes
Content-Type: application/json

{
  "name": "Wardrobe 1",
  "description": "This is a wardrobe",
  "userId": 1
}

### Get all wardrobes
GET {{base_url}}/api/wardrobes

### Get wardrobe by id
GET {{base_url}}/api/wardrobes/1

# Entity: WardrobeItem
This entity represents an item in a wardrobe.

### Create Wardrobe Item
POST {{base_url}}/api/wardrobeItems
Content-Type: application/json

{
  "photoUri": "https://www.google.com",
  "itemName": "Shirt",
  "purchaseDate": "2021-01-01",
  "expiryDate": "2022-01-01",
  "price": 1000,
  "brand": "Zara",
  "category": "Shirt",
  "color": "Blue",
  "size": "M",
  "wardrobeId": 1,
  "userId": 1
}

### Get all wardrobe items
GET {{base_url}}/api/wardrobeItems
